version: '2'
services:
  spring-cloud-gateway:
    build: spring-cloud-gateway/
    container_name: spring-cloud-gateway
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080
  #  eureka-server
  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761
